In [1]:
# Wil put all the imports used in this cell
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta

## S&P 500 AAI Investor Sentiment Data

The data was taken using the quandl API. It is free to use. In order to acess their API you will need to sign up for a free account and they will grant you an API code to use.
From quandl.com: The AAII Investor Sentiment Survey measures the percentage of individual investors who are bullish, bearish, and neutral on the stock market for the next six months; individuals are polled from the ranks of the AAII membership on a weekly basis. Only one vote per member is accepted in each weekly voting period.

I interacted with their API which can be seen in another notebook. I then saved the data into a CSV so I would have an archive.

In [2]:
# will first read in the csv file of S&P Weekly AAI index
SPX=pd.read_csv('SPX_AAI.csv')
SPX.tail()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close
453,2018-09-13,0.320896,0.350746,0.328358,1.000000,0.361794,-0.007462,0.382716,0.484453,0.280978,2894.65,2864.12,2888.92
454,2018-09-20,0.320423,0.359155,0.320423,1.000001,0.362445,0.000000,0.382716,0.484453,0.280978,2912.36,2879.20,2907.95
455,2018-09-27,0.362205,0.326772,0.311024,1.000001,0.371332,0.051181,0.382716,0.484453,0.280978,2940.91,2903.28,2905.97
456,2018-10-04,0.456621,0.292237,0.251142,1.000000,0.382955,0.205479,0.382716,0.484453,0.280978,2939.86,2903.28,2925.51
457,2018-10-11,0.306061,0.339394,0.354545,1.000000,0.376000,-0.048484,0.382716,0.484453,0.280978,2939.86,2784.86,2785.68

In [3]:
# the data starts from January 2010 Until October 11th
# new data is presented every Thursday
# 458 columns and 13 rows
SPX.shape

(458, 13)

In [4]:
SPX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 13 columns):
Date                         458 non-null object
Bullish                      458 non-null float64
Neutral                      458 non-null float64
Bearish                      458 non-null float64
Total                        458 non-null float64
Bullish 8-Week Mov Avg       458 non-null float64
Bull-Bear Spread             458 non-null float64
Bullish Average              458 non-null float64
Bullish Average + St. Dev    458 non-null float64
Bullish Average - St. Dev    458 non-null float64
S&P 500 Weekly High          458 non-null float64
S&P 500 Weekly Low           458 non-null float64
S&P 500 Weekly Close         458 non-null float64
dtypes: float64(12), object(1)
memory usage: 46.6+ KB

In [6]:
# need to change Date column from object to datetime
SPX['Date'] = pd.to_datetime(SPX['Date'])

In [7]:
# This is reported on Thursday so will add a column to make sure this is the case
# 0= Monday, 4 =Friday
SPX['weekday'] = SPX['Date'].dt.dayofweek

In [8]:
SPX.tail()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,weekday
453,2018-09-13,0.320896,0.350746,0.328358,1.000000,0.361794,-0.007462,0.382716,0.484453,0.280978,2894.65,2864.12,2888.92,3
454,2018-09-20,0.320423,0.359155,0.320423,1.000001,0.362445,0.000000,0.382716,0.484453,0.280978,2912.36,2879.20,2907.95,3
455,2018-09-27,0.362205,0.326772,0.311024,1.000001,0.371332,0.051181,0.382716,0.484453,0.280978,2940.91,2903.28,2905.97,3
456,2018-10-04,0.456621,0.292237,0.251142,1.000000,0.382955,0.205479,0.382716,0.484453,0.280978,2939.86,2903.28,2925.51,3
457,2018-10-11,0.306061,0.339394,0.354545,1.000000,0.376000,-0.048484,0.382716,0.484453,0.280978,2939.86,2784.86,2785.68,3

In [9]:
SPX.groupby('weekday').count()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close
weekday,,,,,,,,,,,,,
2,1,1,1,1,1,1,1,1,1,1,1,1,1
3,457,457,457,457,457,457,457,457,457,457,457,457,457

In [10]:
#Need to find the day where it was reported on a Wednesay instead of a Thursday
SPX.loc[SPX.weekday==2]

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,weekday
151,2012-11-28,0.409266,0.247104,0.343629,0.999999,0.335353,0.065637,0.384907,0.488293,0.281522,1409.15,1359.88,1409.93,2

In [11]:
# One more look. For somereason in late November, 2012 it was reported on a Wednesday instead
# of a Thursday
SPX.loc[151,:]

Date                         2012-11-28 00:00:00
Bullish                                 0.409266
Neutral                                 0.247104
Bearish                                 0.343629
Total                                   0.999999
Bullish 8-Week Mov Avg                  0.335353
Bull-Bear Spread                        0.065637
Bullish Average                         0.384907
Bullish Average + St. Dev               0.488293
Bullish Average - St. Dev               0.281522
S&P 500 Weekly High                      1409.15
S&P 500 Weekly Low                       1359.88
S&P 500 Weekly Close                     1409.93
weekday                                        2
Name: 151, dtype: object

In [12]:
#  Every date needs to be switched to a Friday for my strategy to work
SPX.loc[0:150, 'Date'] = SPX["Date"] + timedelta(days=1)
SPX.loc[151:151, 'Date'] = SPX["Date"] + timedelta(days=2)
SPX.loc[152:457, 'Date'] = SPX["Date"] + timedelta(days=1)

In [13]:
SPX.loc[0:150, 'weekday'] = SPX["weekday"] + 1
SPX.loc[151:151, 'weekday'] = SPX["weekday"] + 2
SPX.loc[152:457, 'weekday'] = SPX["weekday"] + 1

In [14]:
# Every day is now a Friday!
SPX.groupby('weekday').count()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close
weekday,,,,,,,,,,,,,
4,458,458,458,458,458,458,458,458,458,458,458,458,458

In [15]:
# This specific date was fixed to a Friday.
SPX.loc[151,:]

Date                         2012-11-30 00:00:00
Bullish                                 0.409266
Neutral                                 0.247104
Bearish                                 0.343629
Total                                   0.999999
Bullish 8-Week Mov Avg                  0.335353
Bull-Bear Spread                        0.065637
Bullish Average                         0.384907
Bullish Average + St. Dev               0.488293
Bullish Average - St. Dev               0.281522
S&P 500 Weekly High                      1409.15
S&P 500 Weekly Low                       1359.88
S&P 500 Weekly Close                     1409.93
weekday                                        4
Name: 151, dtype: object

In [16]:
SPX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 14 columns):
Date                         458 non-null datetime64[ns]
Bullish                      458 non-null float64
Neutral                      458 non-null float64
Bearish                      458 non-null float64
Total                        458 non-null float64
Bullish 8-Week Mov Avg       458 non-null float64
Bull-Bear Spread             458 non-null float64
Bullish Average              458 non-null float64
Bullish Average + St. Dev    458 non-null float64
Bullish Average - St. Dev    458 non-null float64
S&P 500 Weekly High          458 non-null float64
S&P 500 Weekly Low           458 non-null float64
S&P 500 Weekly Close         458 non-null float64
weekday                      458 non-null int64
dtypes: datetime64[ns](1), float64(12), int64(1)
memory usage: 50.2 KB

In [16]:
#The forumla if I wanted to change an entire column
#SPX['Date'] = SPX['Date'].astype(datetime)
#SPX['Date'] = SPX["Date"] + timedelta(days=1)

In [17]:
SPX.isnull().sum()

Date                         0
Bullish                      0
Neutral                      0
Bearish                      0
Total                        0
Bullish 8-Week Mov Avg       0
Bull-Bear Spread             0
Bullish Average              0
Bullish Average + St. Dev    0
Bullish Average - St. Dev    0
S&P 500 Weekly High          0
S&P 500 Weekly Low           0
S&P 500 Weekly Close         0
weekday                      0
dtype: int64

In [18]:
SPX.describe()

,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,weekday
count,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.0
mean,0.365331,0.329759,0.304906,0.999996,0.365824,0.060425,0.384216,0.487207,0.281225,1856.669870,1810.310940,1837.842202,4.0
std,0.080474,0.064790,0.070144,0.000034,0.062419,0.136365,0.000932,0.001529,0.000417,514.326793,504.073292,510.453603,0.0
min,0.177515,0.139500,0.150538,0.999800,0.231430,-0.361300,0.382660,0.484453,0.280002,1033.580000,1021.650000,1030.710000,4.0
25%,0.304380,0.281731,0.255566,1.000000,0.323395,-0.028554,0.383125,0.485674,0.280978,1363.460000,1333.277500,1347.592500,4.0
50%,0.359750,0.325489,0.294810,1.000000,0.363601,0.063397,0.384907,0.488293,0.281522,1908.315000,1845.670000,1883.450000,4.0
75%,0.422326,0.374103,0.345367,1.000000,0.403682,0.153338,0.384907,0.488293,0.281522,2156.034973,2102.015000,2139.367432,4.0
max,0.632800,0.528600,0.570700,1.000100,0.533500,0.468800,0.384907,0.488293,0.281522,2940.910000,2903.280000,2925.510000,4.0

In [19]:
SPX.tail()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,weekday
453,2018-09-14,0.320896,0.350746,0.328358,1.000000,0.361794,-0.007462,0.382716,0.484453,0.280978,2894.65,2864.12,2888.92,4
454,2018-09-21,0.320423,0.359155,0.320423,1.000001,0.362445,0.000000,0.382716,0.484453,0.280978,2912.36,2879.20,2907.95,4
455,2018-09-28,0.362205,0.326772,0.311024,1.000001,0.371332,0.051181,0.382716,0.484453,0.280978,2940.91,2903.28,2905.97,4
456,2018-10-05,0.456621,0.292237,0.251142,1.000000,0.382955,0.205479,0.382716,0.484453,0.280978,2939.86,2903.28,2925.51,4
457,2018-10-12,0.306061,0.339394,0.354545,1.000000,0.376000,-0.048484,0.382716,0.484453,0.280978,2939.86,2784.86,2785.68,4

the data is very clean and accurate with 0 missing values.

## S&P 500 VIX Data

The next key indicator will be the S&P 500 VIX. 
From: https://en.wikipedia.org/wiki/VIXThe 

CBOE Volatility Index, known by its ticker symbol VIX, is a popular measure of the stock market's expectation of volatility implied by S&P 500 index options, calculated and published by the Chicago Board Options Exchange (CBOE). It is colloquially referred to as the fear index or the fear gauge. The current VIX concept formulates a theoretical expectation of stock market volatility in the near future. The current VIX index value quotes the expected annualized change in the S&P 500 index over the following 30 days, as computed from options-based theory and current options-market data

Since I am setting up a weekly trading strategy I will be taking weekly VIX data from January 2010 up till October 2018. The data comes from yahoo finance and I will read in a CSV file.

In [20]:
# will  read in the csv file of S&P Weekly VIX
VIX=pd.read_csv('VIX.csv')
VIX.tail()

           Date       Open       High        Low      Close  Adj Close  Volume
455  2018-09-21  11.760000  13.130000  11.100000  12.410000  12.410000       0
456  2018-09-28  12.590000  15.840000  11.340000  14.220000  14.220000       0
457  2018-10-05  14.290000  28.840000  11.720000  24.980000  24.980000       0
458  2018-10-12  21.629999  26.799999  20.879999  21.309999  21.309999       0
459  2018-10-12  21.629999  26.799999  20.879999  21.309999  21.309999       0

In [21]:
# This data is updated every Friday for the week there is a duplicate row that I will drop
VIX.drop(459, inplace=True)
VIX.tail()

           Date       Open       High        Low      Close  Adj Close  Volume
454  2018-09-14  12.130000  13.750000  11.310000  11.800000  11.800000       0
455  2018-09-21  11.760000  13.130000  11.100000  12.410000  12.410000       0
456  2018-09-28  12.590000  15.840000  11.340000  14.220000  14.220000       0
457  2018-10-05  14.290000  28.840000  11.720000  24.980000  24.980000       0
458  2018-10-12  21.629999  26.799999  20.879999  21.309999  21.309999       0

In [22]:
# January 1st, 2010 happened to fall on a Friday and since I don't have a matching 
# AAI data I will drop the first row and the strategy will begin the 2nd week of Jan.
VIX.drop(0, inplace=True)

In [23]:
VIX.head()

         Date       Open       High        Low      Close  Adj Close  Volume
1  2010-01-08  19.270000  19.459999  16.860001  17.629999  17.629999       0
2  2010-01-15  17.629999  22.299999  17.330000  22.270000  22.270000       0
3  2010-01-22  22.270000  28.010000  22.270000  23.730000  23.730000       0
4  2010-01-29  23.730000  26.320000  21.080000  26.080000  26.080000       0
5  2010-02-05  25.690001  29.219999  23.870001  23.959999  23.959999       0

In [24]:
VIX.shape

(458, 7)

In [25]:
# There is no volume data available for this vix since it's not traded like a stock
# Therefore I will drop it
VIX.drop(['Volume'], axis=1, inplace=True)
VIX.tail()

           Date       Open       High        Low      Close  Adj Close
454  2018-09-14  12.130000  13.750000  11.310000  11.800000  11.800000
455  2018-09-21  11.760000  13.130000  11.100000  12.410000  12.410000
456  2018-09-28  12.590000  15.840000  11.340000  14.220000  14.220000
457  2018-10-05  14.290000  28.840000  11.720000  24.980000  24.980000
458  2018-10-12  21.629999  26.799999  20.879999  21.309999  21.309999

In [26]:
# need to change Date column from object to datetime
VIX['Date'] = pd.to_datetime(VIX['Date'])

In [27]:
VIX['weekday'] = VIX['Date'].dt.dayofweek

In [28]:
# All days are Friday's so no issue here
VIX.groupby('weekday').count()

         Date  Open  High  Low  Close  Adj Close
weekday
4         458   458   458  458    458        458

In [29]:
VIX.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 458 entries, 1 to 458
Data columns (total 7 columns):
Date         458 non-null datetime64[ns]
Open         458 non-null float64
High         458 non-null float64
Low          458 non-null float64
Close        458 non-null float64
Adj Close    458 non-null float64
weekday      458 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 28.6 KB

In [30]:
VIX.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
weekday      0
dtype: int64

the data is very clean and accurate with 0 missing values.

In [31]:
# merged the two datasets on the Date column
df = SPX.merge(VIX, on='Date')
df.tail()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,weekday_x,Open,High,Low,Close,Adj Close,weekday_y
453,2018-09-14,0.320896,0.350746,0.328358,1.000000,0.361794,-0.007462,0.382716,0.484453,0.280978,2894.65,2864.12,2888.92,4,12.130000,13.750000,11.310000,11.800000,11.800000,4
454,2018-09-21,0.320423,0.359155,0.320423,1.000001,0.362445,0.000000,0.382716,0.484453,0.280978,2912.36,2879.20,2907.95,4,11.760000,13.130000,11.100000,12.410000,12.410000,4
455,2018-09-28,0.362205,0.326772,0.311024,1.000001,0.371332,0.051181,0.382716,0.484453,0.280978,2940.91,2903.28,2905.97,4,12.590000,15.840000,11.340000,14.220000,14.220000,4
456,2018-10-05,0.456621,0.292237,0.251142,1.000000,0.382955,0.205479,0.382716,0.484453,0.280978,2939.86,2903.28,2925.51,4,14.290000,28.840000,11.720000,24.980000,24.980000,4
457,2018-10-12,0.306061,0.339394,0.354545,1.000000,0.376000,-0.048484,0.382716,0.484453,0.280978,2939.86,2784.86,2785.68,4,21.629999,26.799999,20.879999,21.309999,21.309999,4

In [32]:
df.shape

(458, 20)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 458 entries, 0 to 457
Data columns (total 20 columns):
Date                         458 non-null datetime64[ns]
Bullish                      458 non-null float64
Neutral                      458 non-null float64
Bearish                      458 non-null float64
Total                        458 non-null float64
Bullish 8-Week Mov Avg       458 non-null float64
Bull-Bear Spread             458 non-null float64
Bullish Average              458 non-null float64
Bullish Average + St. Dev    458 non-null float64
Bullish Average - St. Dev    458 non-null float64
S&P 500 Weekly High          458 non-null float64
S&P 500 Weekly Low           458 non-null float64
S&P 500 Weekly Close         458 non-null float64
weekday_x                    458 non-null int64
Open                         458 non-null float64
High                         458 non-null float64
Low                          458 non-null float64
Close                        458 non-null float64
Adj Close                    458 non-null float64
weekday_y                    458 non-null int64
dtypes: datetime64[ns](1), float64(17), int64(2)
memory usage: 75.1 KB

After further analysis, I realized that there was another issue with my data. The Data from the Quandl API takes the closing price on a Thursday and calls it the "weekly close" so I will need to update the data with full weekly data.

In [34]:
SPX_wk=pd.read_csv('SPX_wk.csv')
SPX_wk.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-01-04,1116.560059,1145.390015,1116.560059,1144.979980,1144.979980,21115350000
1,2010-01-11,1145.959961,1150.410034,1131.390015,1136.030029,1136.030029,21816230000
2,2010-01-18,1136.030029,1150.449951,1090.180054,1091.760010,1091.760010,22618330000
3,2010-01-25,1092.400024,1103.689941,1071.589966,1073.869995,1073.869995,25397670000
4,2010-02-01,1073.890015,1104.729980,1044.500000,1066.189941,1066.189941,25411190000

In [35]:
# Matches the other dataset
SPX.shape

(458, 14)

In [36]:
# need to change Date column from object to datetime
SPX_wk['Date'] = pd.to_datetime(SPX_wk['Date'])

In [37]:
# This is reported on Monday so will add a column to make sure this is the case
# 0= Monday, 4 =Friday
SPX_wk['weekday'] = SPX_wk['Date'].dt.dayofweek

In [38]:
SPX_wk.groupby('weekday').count()

         Date  Open  High  Low  Close  Adj Close  Volume
weekday
0         458   458   458  458    458        458     458

In [39]:
# no worries, it's all the same data. I can give it a Friday timestamp
SPX_wk['Date'] = SPX_wk["Date"] + timedelta(days=4)

In [42]:
SPX_wk['weekday'] = SPX_wk["weekday"] + 4

In [43]:
SPX_wk.head()

,Date,Open,High,Low,Close,Adj Close,Volume,weekday
0,2010-01-08,1116.560059,1145.390015,1116.560059,1144.979980,1144.979980,21115350000,4
1,2010-01-15,1145.959961,1150.410034,1131.390015,1136.030029,1136.030029,21816230000,4
2,2010-01-22,1136.030029,1150.449951,1090.180054,1091.760010,1091.760010,22618330000,4
3,2010-01-29,1092.400024,1103.689941,1071.589966,1073.869995,1073.869995,25397670000,4
4,2010-02-05,1073.890015,1104.729980,1044.500000,1066.189941,1066.189941,25411190000,4

In [44]:
# Now all the dates are correct 
SPX_wk.groupby('weekday').count()

         Date  Open  High  Low  Close  Adj Close  Volume
weekday
4         458   458   458  458    458        458     458

## Finally, Can Merge all the Data

In [45]:
t = df.merge(SPX_wk, on='Date')
t.tail()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,...,Close_x,Adj Close_x,weekday_y,Open_y,High_y,Low_y,Close_y,Adj Close_y,Volume,weekday
453,2018-09-14,0.320896,0.350746,0.328358,1.000000,0.361794,-0.007462,0.382716,0.484453,0.280978,...,11.800000,11.800000,4,2881.389893,2908.300049,2866.780029,2904.979980,2904.979980,15300720000,4
454,2018-09-21,0.320423,0.359155,0.320423,1.000001,0.362445,0.000000,0.382716,0.484453,0.280978,...,12.410000,12.410000,4,2903.830078,2940.909912,2886.159912,2929.669922,2929.669922,18247730000,4
455,2018-09-28,0.362205,0.326772,0.311024,1.000001,0.371332,0.051181,0.382716,0.484453,0.280978,...,14.220000,14.220000,4,2921.830078,2931.149902,2903.280029,2913.979980,2913.979980,16539460000,4
456,2018-10-05,0.456621,0.292237,0.251142,1.000000,0.382955,0.205479,0.382716,0.484453,0.280978,...,24.980000,24.980000,4,2926.290039,2939.860107,2869.290039,2885.570068,2885.570068,17190620000,4
457,2018-10-12,0.306061,0.339394,0.354545,1.000000,0.376000,-0.048484,0.382716,0.484453,0.280978,...,21.309999,21.309999,4,2877.530029,2894.830078,2710.510010,2767.129883,2767.129883,20208740000,4

In [47]:
t.shape

(458, 27)

In [48]:
#time to drop some unnecessary columns
t.drop({'weekday', 'weekday_x', 'weekday_y', 'S&P 500 Weekly High', 'S&P 500 Weekly Low', 'S&P 500 Weekly Close'}, axis=1, inplace=True)

In [50]:
t.columns

Index(['Date', 'Bullish', 'Neutral', 'Bearish', 'Total',
       'Bullish 8-Week Mov Avg', 'Bull-Bear Spread', 'Bullish Average',
       'Bullish Average + St. Dev', 'Bullish Average - St. Dev', 'Open_x',
       'High_x', 'Low_x', 'Close_x', 'Adj Close_x', 'Open_y', 'High_y',
       'Low_y', 'Close_y', 'Adj Close_y', 'Volume'],
      dtype='object')

In [51]:
#rename columns
t = t.rename(columns={'Open_x':'VIX Open', 'High_x':'VIX High', 
                           'Low_x':'VIX Low',
                           'Close_x':'VIX Close','Adj Close_x':'VIX Adj Close',
                           'Open_y':'SPX Open', 'High_y':'SPX High', 'Low_y':'SPX Low',
                           'Close_y':'SPX close', 'Adj Close_y': 'SPX ADj Close'
                          })

In [52]:
t.head()

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,...,VIX High,VIX Low,VIX Close,VIX Adj Close,SPX Open,SPX High,SPX Low,SPX close,SPX ADj Close,Volume
0,2010-01-08,0.4100,0.3300,0.2600,1.0,0.423275,0.1500,0.384907,0.488293,0.281522,...,19.459999,16.860001,17.629999,17.629999,1116.560059,1145.390015,1116.560059,1144.979980,1144.979980,21115350000
1,2010-01-15,0.4744,0.2564,0.2692,1.0,0.429163,0.2052,0.384907,0.488293,0.281522,...,22.299999,17.330000,22.270000,22.270000,1145.959961,1150.410034,1131.390015,1136.030029,1136.030029,21816230000
2,2010-01-22,0.4000,0.2526,0.3474,1.0,0.427088,0.0526,0.384907,0.488293,0.281522,...,28.010000,22.270000,23.730000,23.730000,1136.030029,1150.449951,1090.180054,1091.760010,1091.760010,22618330000
3,2010-01-29,0.3500,0.2833,0.3667,1.0,0.418863,-0.0167,0.384907,0.488293,0.281522,...,26.320000,21.080000,26.080000,26.080000,1092.400024,1103.689941,1071.589966,1073.869995,1073.869995,25397670000
4,2010-02-05,0.2923,0.2769,0.4308,1.0,0.402050,-0.1385,0.384907,0.488293,0.281522,...,29.219999,23.870001,23.959999,23.959999,1073.890015,1104.729980,1044.500000,1066.189941,1066.189941,25411190000

In [55]:
t.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 458 entries, 2010-01-08 to 2018-10-12
Data columns (total 20 columns):
Bullish                      458 non-null float64
Neutral                      458 non-null float64
Bearish                      458 non-null float64
Total                        458 non-null float64
Bullish 8-Week Mov Avg       458 non-null float64
Bull-Bear Spread             458 non-null float64
Bullish Average              458 non-null float64
Bullish Average + St. Dev    458 non-null float64
Bullish Average - St. Dev    458 non-null float64
VIX Open                     458 non-null float64
VIX High                     458 non-null float64
VIX Low                      458 non-null float64
VIX Close                    458 non-null float64
VIX Adj Close                458 non-null float64
SPX Open                     458 non-null float64
SPX High                     458 non-null float64
SPX Low                      458 non-null float64
SPX close                    458 non-null float64
SPX ADj Close                458 non-null float64
Volume                       458 non-null int64
dtypes: float64(19), int64(1)
memory usage: 75.1 KB

In [54]:
t.to_csv('./SPX_trial.csv')

Now that I have my main data, I will create new columns, taking advantage of Pandas time series features

In [53]:
# need to set date as the index in order to take advantage of Pandas Features
t.set_index('Date', inplace = True )
t.head()

,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,VIX Open,VIX High,VIX Low,VIX Close,VIX Adj Close,SPX Open,SPX High,SPX Low,SPX close,SPX ADj Close,Volume
Date,,,,,,,,,,,,,,,,,,,,
2010-01-08,0.4100,0.3300,0.2600,1.0,0.423275,0.1500,0.384907,0.488293,0.281522,19.270000,19.459999,16.860001,17.629999,17.629999,1116.560059,1145.390015,1116.560059,1144.979980,1144.979980,21115350000
2010-01-15,0.4744,0.2564,0.2692,1.0,0.429163,0.2052,0.384907,0.488293,0.281522,17.629999,22.299999,17.330000,22.270000,22.270000,1145.959961,1150.410034,1131.390015,1136.030029,1136.030029,21816230000
2010-01-22,0.4000,0.2526,0.3474,1.0,0.427088,0.0526,0.384907,0.488293,0.281522,22.270000,28.010000,22.270000,23.730000,23.730000,1136.030029,1150.449951,1090.180054,1091.760010,1091.760010,22618330000
2010-01-29,0.3500,0.2833,0.3667,1.0,0.418863,-0.0167,0.384907,0.488293,0.281522,23.730000,26.320000,21.080000,26.080000,26.080000,1092.400024,1103.689941,1071.589966,1073.869995,1073.869995,25397670000
2010-02-05,0.2923,0.2769,0.4308,1.0,0.402050,-0.1385,0.384907,0.488293,0.281522,25.690001,29.219999,23.870001,23.959999,23.959999,1073.890015,1104.729980,1044.500000,1066.189941,1066.189941,25411190000

In [40]:
t['5 EMA'] = t['S&P 500 Weekly Close'].ewm(span=5).mean()

In [42]:
df.tail()

,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,weekday_x,Open,High,Low,Close,Adj Close,weekday_y,5 EMA
Date,,,,,,,,,,,,,,,,,,,,
2018-09-14,0.320896,0.350746,0.328358,1.000000,0.361794,-0.007462,0.382716,0.484453,0.280978,2894.65,2864.12,2888.92,4,12.130000,13.750000,11.310000,11.800000,11.800000,4,2876.087284
2018-09-21,0.320423,0.359155,0.320423,1.000001,0.362445,0.000000,0.382716,0.484453,0.280978,2912.36,2879.20,2907.95,4,11.760000,13.130000,11.100000,12.410000,12.410000,4,2886.708189
2018-09-28,0.362205,0.326772,0.311024,1.000001,0.371332,0.051181,0.382716,0.484453,0.280978,2940.91,2903.28,2905.97,4,12.590000,15.840000,11.340000,14.220000,14.220000,4,2893.128793
2018-10-05,0.456621,0.292237,0.251142,1.000000,0.382955,0.205479,0.382716,0.484453,0.280978,2939.86,2903.28,2925.51,4,14.290000,28.840000,11.720000,24.980000,24.980000,4,2903.922529
2018-10-12,0.306061,0.339394,0.354545,1.000000,0.376000,-0.048484,0.382716,0.484453,0.280978,2939.86,2784.86,2785.68,4,21.629999,26.799999,20.879999,21.309999,21.309999,4,2864.508352

In [ ]:
df.ewm(span=10).mean()